#!/bin/sh

case "$1" in
	start)
		printf "load wifi modules: "
		rk_wifi_init || true
		wl PM 0

		;;
	stop)

		echo 0 > /sys/class/rfkill/rfkill0/state

		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
